// disappointed_professor_data.js
export const disappointedProfessorData = {
    "UA": {
        "Розчарований Професор": [
            "🧐 Звісно, [NAME]. Ваші [AMOUNT] були прийняті. Це, безумовно, не покриє моїх академічних амбіцій, але для первинного фінансування — прийнятно. Дякую. 🧐\nЗ повагою Ваш Розчарований Професор [CREATORNAME].",
            "🙄 Пане [NAME], дякую. Це [AMOUNT]? Я б не назвав це революцією, скоріше — незначним фактором. Втім, як гіпотеза фінансової підтримки, вона заслуговує на увагу. 🙄\nЗ повагою Ваш Розчарований Професор [CREATORNAME].",
            "🧐 Цей фінансовий жест у розмірі [AMOUNT] від [NAME]... Він не відповідає моїм високим очікуванням, але, гадаю, я зможу інтегрувати його в бюджет. Не забудьте про наступний транш. 🧐\nЗ повагою Ваш Розчарований Професор [CREATORNAME].",
            "🙄 Моя асистентка щойно повідомила про надходження [AMOUNT] від [NAME]. Це мінімалістично, але, як ви знаєте, навіть з мінімальних ресурсів можна створити щось більш-менш пристойне. Дякую. 🙄\nЗ повагою Ваш Розчарований Професор [CREATORNAME].",
            "🙄 [NAME], Ваша сума [AMOUNT] — це цікавий зразок фінансового мінімалізму. Це не фінансування моєї монографії, але для чашки кави підійде. Дякую. 🧐\nЗ повагою Ваш Розчарований Професор [CREATORNAME].",
            "🧐 Я класифікую [AMOUNT] від [NAME] як \"Тестовий Грант\". Я очікую на Повномасштабний Грант у п'ять разів більшого обсягу. Не зупиняйтеся на поверхневому аналізі! 🙄\nЗ повагою Ваш Розчарований Професор [CREATORNAME].",
            "🙄 [NAME]. [AMOUNT]. Це не Рівень \"А\" фінансової підтримки. Це, швидше, поблажливе кивання. Я змушений прийняти це, але лише тому, що не люблю порушувати протоколи. 🧐\nЗ повагою Ваш Розчарований Професор [CREATORNAME].",
            "🙄 Ці [AMOUNT] від [NAME] — це як невеликий внесок у велику науку. Нехай він послужить прикладом для інших. Але не думайте, що це кінець. 🙄\nЗ повагою Ваш Розчарований Професор [CREATORNAME].",
            "🧐 [NAME]! [AMOUNT]! Це не \"Теорія Всього\" у фінансовому плані. Це фрагмент мого майбутнього бюджетного рівняння. Дякую за цей невеликі, але необхідні, дані. 🧐\nЗ повагою Ваш Розчарований Професор [CREATORNAME].",
            "🙄 [NAME], я проаналізував Вашу транзакцію [AMOUNT]. Вона демонструє базове розуміння філантропії. Працюйте над поглибленням цього розуміння. Оцінка: \"задовільно\". 🙄\nЗ повагою Ваш Розчарований Професор [CREATORNAME].",
        ]
    },
    "EN": {
        // ВИПРАВЛЕНО: Ключ для EN тепер 'The Disappointed Professor'
        "The Disappointed Professor": [
            "🧐 Certainly, [NAME]. Your [AMOUNT] has been accepted. This will, decidedly, not cover my academic ambitions, but for initial financing—it is acceptable. Thank you. 🧐\nSincerely, Your Disappointed Professor [CREATORNAME].",
            "🙄 Mr./Ms. [NAME], thank you. This [AMOUNT]? I would not term it a revolution, but rather a negligible factor. However, as a hypothesis of financial support, it warrants attention. 🙄\nSincerely, Your Disappointed Professor [CREATORNAME].",
            "🧐 This financial gesture of [AMOUNT] from [NAME]... It does not align with my elevated expectations, but I suppose I can integrate it into the budget. Do not forget the next tranche. 🧐\nSincerely, Your Disappointed Professor [CREATORNAME].",
            "🙄 My research assistant just notified me of the ingress of [AMOUNT] from [NAME]. It is minimalist, but as you know, even with minimal resources, one can fabricate something somewhat decent. Thank you. 🙄\nSincerely, Your Disappointed Professor [CREATORNAME].",
            "🙄 [NAME], your sum of [AMOUNT] is an intriguing specimen of financial minimalism. It is not funding for my monograph, but it will suffice for a cup of mediocre coffee. Thank you. 🧐\nSincerely, Your Disappointed Professor [CREATORNAME].",
            "🧐 I shall classify [AMOUNT] from [NAME] as a \"Test Grant.\" I anticipate a Full-Scale Grant of five times the volume. Do not cease at superficial analysis! 🙄\nSincerely, Your Disappointed Professor [CREATORNAME].",
            "🙄 [NAME]. [AMOUNT]. This does not qualify as Level \"A\" financial endorsement. It is, rather, a condescending nod. I am compelled to accept it, but only because I abhor violating protocols. 🧐\nSincerely, Your Disappointed Professor [CREATORNAME].",
            "🙄 This [AMOUNT] from [NAME] is like a minor contribution to a grand science. Let it serve as an example to others. But do not presume this is the conclusion. 🙄\nSincerely, Your Disappointed Professor [CREATORNAME].",
            "🧐 [NAME]! [AMOUNT]! This is not the \"Theory of Everything\" in the financial realm. It is a fragment of my future budgetary equation. Thank you for this small, but necessary, data. 🧐\nSincerely, Your Disappointed Professor [CREATORNAME].",
            "🙄 [NAME], I have analyzed your transaction [AMOUNT]. It exhibits a rudimentary comprehension of philanthropy. Endeavor to deepen this comprehension. Grade: \"Satisfactory.\" 🙄\nSincerely, Your Disappointed Professor [CREATORNAME].",
        ]
    }
};
