// vacuum_salesman_data.js
export const vacuumSalesmanData = {
    "UA": {
        "Продавець Пилососів": [
            "💼 Вітаю, [NAME]! Ваш [AMOUNT] – це найкраща інвестиція! Це лише перший крок! Чи не бажаєте подвоїти цю суму прямо зараз і отримати ексклюзивну безкоштовну доставку нашої вдячності? Гарантую!\n🤝\nЗ повагою\nВаш Продавець Пилососів [CREATORNAME].",
            "💰 [NAME]! Ваш [AMOUNT]! Неймовірно! Але почекайте, Ви не скористалися нашим пакетом \"Gold\"! Просто доплатіть $5 і отримайте бонус у вигляді моєї вічної вдячності!\n💰\nЗ повагою\nВаш Продавець Пилососів [CREATORNAME].",
            "💼 Дякую, [NAME]! Цей [AMOUNT] – це Ваша перша покупка! Я гарантую, Ви не пошкодуєте! А як щодо того, щоб оформити автоматичне списання такої ж суми щотижня? Це просто, як двічі два!\n🚀\nЗ повагою\nВаш Продавець Пилососів [CREATORNAME].",
            "💰 [AMOUNT] від [NAME]! Фантастика! Ця сума говорить про Ваш смак! Уявіть, якби Ви купили два таких! Це подвійна фантастика! Поспішайте, поки акція не закінчилася!\n🤝\nЗ повагою\nВаш Продавець Пилососів [CREATORNAME].",
            "💼 [NAME], Ваш [AMOUNT] прийнято! Але це \"стандартний\" пакет. Наша преміальна пропозиція включає пожиттєву гарантію за лише $100. Давайте оформимо це зараз, поки час не вийшов!\n💰\nЗ повагою\nВаш Продавець Пилососів [CREATORNAME].",
            "🚀 [NAME]! [AMOUNT]! Я знаю, що Ви хочете більшого! Ви заслуговуєте на кращий продукт! Просто додайте ще [AMOUNT], і ми зробимо апгрейд Вашого донату до рівня \"Бог\"!\n🚀\nЗ повагою\nВаш Продавець Пилососів [CREATORNAME].",
            "🤩 [AMOUNT] від [NAME]! Блискуче рішення! Тепер, щоб отримати максимум вигоди, Вам потрібно лише підтвердити наступний платіж! Я зарезервував для Вас найкращу пропозицію!\n🤝\nЗ повагою\nВаш Продавець Пилососів [CREATORNAME].",
            "🚀 [NAME]! Ваш [AMOUNT]! Фантастика! А тепер найголовніше: подвоюючи Ваш внесок зараз, Ви автоматично стаєте учасником секретного клубу, про який не можна говорити!\n💰\nЗ повагою\nВаш Продавець Пилососів [CREATORNAME].",
            "💼 [NAME]! [AMOUNT]! Ви розумна людина! Ви бачите переваги! Я чекаю, поки Ви скажете \"Так\" на максимальний донат, який зробить нас обох мільйонерами! Це не пропозиція, це угода!\n🚀\nЗ повагою\nВаш Продавець Пилососів [CREATORNAME].",
            "💼 [NAME], Ваш донат [AMOUNT]! Це лише анонс! Не проґавте ОБМЕЖЕНУ В ЧАСІ ПРОПОЗИЦІЮ! Я вже почав відлік! ЧАС ПІШОВ! ПОТРІБНО БІЛЬШЕ ГРОШЕЙ!\n🤝\nЗ повагою\nВаш Продавець Пилососів [CREATORNAME].",
        ]
    },
    "EN": {
        // ВИПРАВЛЕНО: Ключ для EN тепер 'The Vacuum Salesman'
        "The Vacuum Salesman": [
            "💼 Greetings, [NAME]! Your [AMOUNT] is the best investment! This is only the first step! Would you like to double this amount right now and get exclusive free shipping on our gratitude? Guaranteed!\n🤝\nSincerely,\nYour Vacuum Salesman [CREATORNAME].",
            "💰 [NAME]! Your [AMOUNT]! Incredible! But wait, you didn't use our \"Gold\" package! Just pay $5 extra and receive a bonus in the form of my eternal gratitude!\n💰\nSincerely,\nYour Vacuum Salesman [CREATORNAME].",
            "💼 Thank you, [NAME]! This [AMOUNT] is your first purchase! I guarantee you won't regret it! And how about setting up an automatic weekly withdrawal of the same amount? It's as easy as pie!\n🚀\nSincerely,\nYour Vacuum Salesman [CREATORNAME].",
            "💰 [AMOUNT] from [NAME]! Fantastic! This amount speaks to your taste! Imagine if you bought two of these! That's double the fantastic! Hurry, before the promotion ends!\n🤝\nSincerely,\nYour Vacuum Salesman [CREATORNAME].",
            "💼 [NAME], your [AMOUNT] has been accepted! But this is the \"standard\" package. Our premium offer includes a lifetime warranty for only $100. Let's process this now before time runs out!\n💰\nSincerely,\nYour Vacuum Salesman [CREATORNAME].",
            "🚀 [NAME]! [AMOUNT]! I know you want more! You deserve a better product! Just add another [AMOUNT], and we'll upgrade your donation to the \"God\" level!\n🚀\nSincerely,\nYour Vacuum Salesman [CREATORNAME].",
            "🤩 [AMOUNT] from [NAME]! Brilliant decision! Now, to get the maximum benefit, you just need to confirm the next payment! I've reserved the best offer for you!\n🤝\nSincerely,\nYour Vacuum Salesman [CREATORNAME].",
            "🚀 [NAME]! Your [AMOUNT]! Fantastic! And now the main thing: by doubling your contribution now, you automatically become a member of a secret club that cannot be talked about!\n💰\nSincerely,\nYour Vacuum Salesman [CREATORNAME].",
            "💼 [NAME]! [AMOUNT]! You are a smart person! You see the advantages! I'm waiting for you to say \"Yes\" to the maximum donation that will make us both millionaires! This is not a proposal; it's a deal!\n🚀\nSincerely,\nYour Vacuum Salesman [CREATORNAME].",
            "💼 [NAME], your donation [AMOUNT]! This is just an announcement! Don't miss the LIMITED TIME OFFER! I've already started the countdown! TIME IS RUNNING OUT! MORE MONEY IS NEEDED!\n🤝\nSincerely,\nYour Vacuum Salesman [CREATORNAME].",
        ]
    }
};
